# Site Settings
name: Isaimini
title: Isaimini | Download and Watch Latest Tamil, Telugu, Malayalam, Hindi
  Movies at High Quality.
description: Download and Watch Latest Tamil, Telugu, Malayalam, Hindi Movies at
  High Quality. Tamil Latest Movies and Tamil Dubbed Movies Free Download in HD
  Online Watching Free Tentrockers
tags:
  - isaimini
  - moviesda
  - movies
  - tamilrockers
  - hindi
  - telugu
  - malaylam
  - hollywood
  - bollywood
  - torrent
  - 720p
  - 1gb
  - 400mb
  - serials
  - series
  - cricket
  - online
  - movierulz
  - 123movies
  - isaidub
  - kuttymovies
  - kuttyrockers
  - srirockers
  - wetransfer
  - dubbed
  - telegram
  - tamilkit
  - movieskit
  - proxy
show_hero: false
paginate: 30
menu:
  - title: Home
    url: /
  - url: /category/Tamil/
    title: Tamil Movies
  - title: Telugu Movies
    url: /category/Telugu/
  - url: /category/Hindi/
    title: Hindi Movies
  - title: English Movies
    url: /category/Hollywood/
  - url: /category/Series/
    title: Web Series
  - title: Telegram
    url: tg://resolve/?domain=isaiminidownload
email: ""
disqus_username: disqus_username


# Social Media Settings
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hd.isaiminiweb.online" # the base hostname & protocol for your site
google_analytics: "UA-179466109-1"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Proxies
proxy0: "https://tamilmv.isaimini.live" # the base hostname & protocol for your sit
proxy1: "https://movies.isaimini.live" # the base hostname & protocol for your site
proxy2: "https://moviesda.isaimini.live" # the base hostname & protocol for your site
proxy3: "https://tamilyogi.isaimini.live" # the base hostname & protocol for your site
proxy4: "http://tamilyogi.isaiminiweb.online"
proxy5: "http://tamilmv.isaiminiweb.online"
proxy6: "http://moviesda.isaiminiweb.online"
proxy7: "http://movies.isaiminiweb.online"
proxy8: "http://tamilgun.isaiminiweb.online"
proxy9: "http://tamilrockers.isaiminiweb.online"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-feed
  - jekyll-sitemap 

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.0

feed:
  posts_limit: 2000
